# Generated by Django 4.2.2 on 2023-06-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='learning',
            field=models.TextField(blank=True),
        ),
    ]
