# Generated by Django 4.2.2 on 2023-06-24 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../image/upload/v1/6_man_shorthair_blackhair_happy_carzgj.jpg', upload_to='images/'),
        ),
    ]
