# Generated by Django 4.2.2 on 2023-11-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='learning',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='tutor_sessions',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='Parent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
