# Generated by Django 4.0.5 on 2023-11-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='password1',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
