# Generated by Django 4.2.2 on 2023-11-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_useraccount_learning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='Parent',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
