# Generated by Django 4.2.2 on 2023-06-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_learning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='bio',
        ),
    ]
