# Generated by Django 4.2.2 on 2023-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_content_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
