# Generated by Django 4.0.5 on 2023-11-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_useraccount_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='Parent',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='owner',
        ),
    ]
