# Generated by Django 4.2.2 on 2023-07-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_useraccount_options_useraccount_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='learning_field',
            new_name='learning',
        ),
    ]
