# Generated by Django 4.2.2 on 2023-09-12 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_learning_field_useraccount_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='owner',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
