# Generated by Django 4.0.5 on 2023-11-27 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='username1',
        ),
    ]
