# Generated by Django 4.0.5 on 2023-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_useraccount_options_alter_useraccount_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='useraccount',
            old_name='username2',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='useraccount',
            table=None,
        ),
    ]
