# Generated by Django 4.0.5 on 2024-01-02 23:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reviews.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=256)),
                ('slug', models.SlugField(unique=True, verbose_name='Feature')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=30, verbose_name='Product Type')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
                ('colors', models.CharField(blank=True, max_length=20, null=True, verbose_name='Color')),
                ('price_range', models.CharField(blank=True, max_length=100, verbose_name='Product Price Range')),
                ('slug', models.SlugField(unique=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=200, verbose_name='name_of_product')),
                ('release_year', models.SmallIntegerField(validators=[reviews.validators.year_validator], verbose_name='Release year')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviews.category')),
            ],
            options={
                'verbose_name': 'Product Name',
                'verbose_name_plural': 'Product Names',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default=None, null=True)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, '10'), django.core.validators.MinValueValidator(1, '1')])),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Pub date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_name', to='reviews.title')),
                ('title', models.ForeignKey(default=None, max_length=40, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.title')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique_author_review'),
        ),
    ]
