# Generated by Django 4.0.5 on 2023-12-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='name_of_product',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
    ]
