# Generated by Django 4.0.5 on 2024-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='titles/', verbose_name='Image'),
        ),
    ]
