# Generated by Django 4.0.5 on 2024-01-13 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10, '10'), django.core.validators.MinValueValidator(1, '1')]),
        ),
    ]
