# Generated by Django 4.0.5 on 2023-12-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_name_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
