# Generated by Django 4.0.5 on 2024-01-21 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_productname_remove_title_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10, '10'), django.core.validators.MinValueValidator(1, '1')]),
        ),
    ]
