# Generated by Django 4.0.5 on 2023-12-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Product Name', 'verbose_name_plural': 'Product Names'},
        ),
    ]
